In [1]:
import numpy as np

In [2]:
arr = [[1, 2, 4, 29], [3, 4, 6, 1]]

In [22]:
arr

[[1, 2, 4, 29], [3, 4, 6, 1]]

In [20]:
type(A)

numpy.matrix

In [23]:
A = np.matrix('1 2 3; 4 5 6')
print(A)
C = 3 * A
print(C)


[[1 2 3]
 [4 5 6]]
[[ 3  6  9]
 [12 15 18]]


In [25]:
A = np.matrix('1 6 3; 8 2 7')
B = np.matrix('8 1 5; 6 9 12')
C = A + B
print(C)
print(type(C))

[[ 9  7  8]
 [14 11 19]]
<class 'numpy.matrix'>


In [32]:
A = np.matrix('1 2 3; 4 5 6')
print("Size A = ", A.shape)

B = np.matrix('7 8; 9 1; 2 3')
print("Size B = ", B.shape)
C = A.dot(B)

#### a.b / <a.b>

Size A =  (2, 3)
Size B =  (3, 2)


In [34]:
A.T.shape

(3, 2)

In [35]:
type(A.T)

numpy.matrix

In [27]:
C

matrix([[31, 19],
        [85, 55]])

In [36]:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
C = np.matrix('2 4; 7 8')
L = A.dot(B.dot(C))
R = (A.dot(B)).dot(C)

In [37]:
L

matrix([[192, 252],
        [436, 572]])

In [38]:
R

matrix([[192, 252],
        [436, 572]])

In [39]:
L == R

matrix([[ True,  True],
        [ True,  True]])

In [ ]:
####   A * B * C = A * (B * C) = (A * B) * C
#### 